export const LoremIpsum = () => {
    return (
        <>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas convallis in purus vitae placerat. Curabitur auctor ex purus, sit amet molestie nisl tempus quis. Nulla aliquet varius massa non bibendum. Sed finibus vulputate metus eget auctor. Nunc fringilla volutpat fringilla. Fusce libero mauris, cursus nec efficitur sit amet, ornare at justo. Maecenas scelerisque nisi malesuada diam congue malesuada. Sed bibendum elit leo, ac rhoncus nisl gravida tincidunt. Duis est leo, efficitur sed condimentum vel, viverra non diam. Phasellus sed felis ac justo commodo lobortis vel eget leo. Sed eget sapien non ante mollis iaculis. Quisque at justo nulla. Proin eu dui sed lorem posuere tristique. </p>
            <p>Aliquam arcu lectus, feugiat ut placerat et, ornare ac dolor. Etiam sodales, nibh eget feugiat cursus, massa lorem auctor lorem, vel venenatis dui est a purus. In semper suscipit enim, non congue diam fermentum vitae. Donec rutrum, massa vitae aliquam gravida, nunc diam auctor est, eu placerat nulla est et urna. Etiam at massa in elit ornare porttitor id sed justo. Maecenas gravida ac urna ac pellentesque. Vivamus pulvinar lectus augue, at feugiat mauris pretium et. Maecenas dapibus massa sem, id commodo eros tempor eu. Integer accumsan fringilla nulla, eu congue magna cursus nec. Pellentesque faucibus tellus a vehicula vehicula. </p>
            <p>Duis a odio et ligula aliquam ornare. Nullam sed neque iaculis, aliquet elit quis, tempor enim. Donec rutrum nunc et ante lacinia, in vestibulum justo cursus. Sed congue purus facilisis, faucibus felis posuere, malesuada est. Mauris et laoreet lorem, nec accumsan nisi. Nullam a ipsum mauris. Proin dapibus gravida pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. </p>
            <p>Ut accumsan pulvinar lectus, ut dictum felis dapibus suscipit. Pellentesque feugiat, nisl congue congue faucibus, ante nisi imperdiet mi, at dictum augue elit vitae eros. Aliquam erat est, blandit at ipsum vitae, elementum ullamcorper sapien. Curabitur sed vehicula nunc, non tincidunt felis. Nam varius rutrum lacus, a porttitor orci sollicitudin vel. Phasellus sollicitudin ipsum mollis ornare laoreet. Vivamus mollis, ligula ut lobortis cursus, diam eros sodales quam, et ultricies tortor dolor in nulla. In commodo rutrum nulla, vel pulvinar ligula fermentum sed. Donec quis purus justo. In id tortor a orci consequat iaculis. Mauris convallis ultricies tempor. Sed a magna id ex luctus egestas vitae non est. Aenean pellentesque ex lacus, id commodo arcu congue eu. Fusce gravida magna felis, in pretium quam ornare at. Quisque lorem urna, ornare porttitor est vitae, scelerisque aliquet orci. </p>
            <p>Suspendisse non metus at elit tempor condimentum in ac ante. Fusce tempus vestibulum risus, eget efficitur elit vehicula vel. Mauris consectetur risus eget eros iaculis, non rhoncus orci ullamcorper. Ut eu dictum ligula. Nam gravida turpis enim, id auctor orci efficitur eget. Suspendisse rhoncus odio a mattis placerat. Sed id efficitur purus, ac aliquam elit. Etiam mi diam, consequat at dictum a, vulputate a odio. Fusce pulvinar nisi non nunc mattis sollicitudin. Aliquam vehicula diam non viverra consectetur. </p>
            <p>Suspendisse sed finibus turpis. Fusce tortor mi, vulputate quis condimentum et, tincidunt eget sapien. Ut in arcu felis. Duis vel leo at sapien feugiat varius. Etiam nec lorem eu felis consequat egestas vel ac lectus. Sed dapibus massa rhoncus est mattis, a hendrerit metus porta. Vivamus non viverra elit. Vivamus ac tellus eu purus fermentum ornare in vel tortor. Pellentesque dolor nisl, ornare sit amet sem et, cursus gravida tortor. </p>
            

        </>
    )
}